user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation

app.producto:
    resource: "@AppBundle/Controller/ProductoController.php"
    type: annotation
    prefix: /indice